name: Runner
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      microservice:
        required: true
        type: string

jobs:
  prepare_deployment:
    name: Prepare deployment - ${{inputs.microservice}}
    runs-on: ubuntu-latest
    outputs:
      tech: ${{ steps.get_tech.outputs.tech }}
    steps:
      - uses: actions/checkout@v4

      - name: Determine Tech
        id: get_tech
        run: |
<<<<<<<< HEAD:.github/workflows/images-without-dependencies.yml
          service="${{inputs.microservice}}"
          if [[ "$service" == "backend" ]]; then
========
          folder_changed="${{inputs.microservice}}"
          if [[ "$folder_changed" == "agent-manager" || "$folder_changed" == "aws" || "$folder_changed" == "bitdefender" || "$folder_changed" == "office365" || "$folder_changed" == "sophos" || "$folder_changed" == "log-auth-proxy" ]]; then
            tech="golang"
          elif [[ "$folder_changed" == "backend" ]]; then
>>>>>>>> origin/main:.github/workflows/used-runner.yml
            tech="java-11"
          elif [[ "$service" == "frontend" ]]; then
            tech="frontend"
          elif [[ "$service" == "user-auditor" || "web-pdf" ]]; then
            tech="java"
          else
            tech="unknown"
          fi
          echo $tech
          echo "::set-output name=tech::$tech"
        shell: bash
  
  frontend_deployment:
    name: Frontend deployment
    needs: prepare_deployment
    if: ${{ needs.prepare_deployment.outputs.tech == 'frontend' }}
    uses: ./.github/workflows/used-docker-frontend.yml
    with:
      image_name: ${{ inputs.microservice }}
      environment: ${{inputs.tag}}-community

  golang_deployment:
    name: Golang deployment
    needs: prepare_deployment
    if: ${{ needs.prepare_deployment.outputs.tech == 'golang' }}
    uses: ./.github/workflows/used-docker-golang.yml
    with:
      image_name: ${{ inputs.microservice }}
      environment: ${{inputs.tag}}-community

  java_11_deployment:
    name: Java 11 deployment
    needs: prepare_deployment
    if: ${{ needs.prepare_deployment.outputs.tech == 'java-11' }}
    uses: ./.github/workflows/used-docker-java-11-new.yml
    with:
      image_name: ${{ inputs.microservice }}
      tag: ${{inputs.tag}}-community
      version: ${{inputs.tag}}

  java_deployment:
    name: Java deployment
    needs: prepare_deployment
    if: ${{ needs.prepare_deployment.outputs.tech == 'java' }}
    uses: ./.github/workflows/used-docker-java.yml
    with:
      image_name: ${{ inputs.microservice }}
      environment: ${{inputs.tag}}-community
